# super user permissions
sudo: required
services:
  # travis will install docker
  - docker

before_install:
  - docker build -f Dockerfile.dev -t dmazaleuskaya/docker-react .

script:
  - docker run -e CI=true dmazaleuskaya/docker-react npm run test
